export const START_SALE = "START_SALE";

export const CREATE_PURCHASE = "CREATE_PURCHASE";
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const PURCHASE_FAILURE = "PURCHASE_FAILURE";

export const REQUEST_WALLET = "REQUEST_WALLET";
export const REQUEST_WALLET_SUCCESS = "REQUEST_WALLET_SUCCESS";
export const REQUEST_WALLET_FAILURE = "REQUEST_WALLET_FAILURE";

export const TOKEN_ASSIGNED = "TOKEN_ASSIGNED";

export const ERROR = "ERROR";
